version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    restart: always
    ports:
      - "5002:80"
    networks:
      - apachecve
      
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    restart: always
    networks:
      - apachecve
      
  redis:
    image: "redis:alpine"
    networks:
      - apachecve

networks:
  apachecve:
    driver: bridge
