version: '3'
services:
 wangy-app:
   build:
     context: .
     dockerfile: Dockerfile.app
   deploy:
     resources:
       limits:
         cpus: "1"
         memory: "1024M"
       reservations:
         cpus: "0.25"
         memory: "256M"
   restart: on-failure
   networks:
     - wangy-network

  wangy-nginx:
   build:
     context: .
     dockerfile: Dockerfile.nginx
   restart: on-failure
   ports:
     - "5003:80"
   networks:
     - wangy-network

networks:
  wangy-network:
    driver: bridge