version: '3'
services:
  nuklir-app:
   build:
     context: .
     dockerfile: Dockerfile.app
   deploy:
     resources:
       limits:
         cpu: "1"
         memory: "1024M"
       reservations:
         cpu: "0.25"
         memory: "256M"
   restart: on-failure
   networks:
     - nuklir-network

  nuklir-nginx:
   build:
     context: .
     dockerfile: Dockerfile.nginx
   restart: on-failure
   ports:
     - "5002:80"
   networks:
     - nuklir-network

networks:
  nuklir-network:
    driver: bridge
