version: '3'
services:
  kijang-satu-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    depends_on:
      - kijang-satu-mongo
    networks:
      - kijang-satu-network

  kijang-satu-nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "5004:80"
    networks:
      - kijang-satu-network

  kijang-satu-mongo:
    image : mongo:4.4.6
    restart: always
    networks:
      - kijang-satu-network

networks:
  kijang-satu-network:
    driver: bridge
