version: '3'
services:
  admin-panel-app:
   build:
     context: .
     dockerfile: Dockerfile.app
   restart: on-failure
   networks:
     - admin-panel-network

  admin-panel-nginx:
   build:
     context: .
     dockerfile: Dockerfile.nginx
   restart: on-failure
   ports:
     - "10002:80"
   networks:
     - admin-panel-network

networks:
  admin-panel-network:
    driver: bridge
