version: '3'
services:
  admin-panel-app:
   build:
     context: .
     dockerfile: Dockerfile.app
   deploy:
     resources:
       limits:
         cpus: "1"
         memory: "1024M"
       reservations:
         cpus: "0.25"
         memory: "256M"
   restart: on-failure
   networks:
     - admin-panel-network

  admin-panel-nginx:
   build:
     context: .
     dockerfile: Dockerfile.nginx
   restart: on-failure
   ports:
     - "5003:80"
   networks:
     - admin-panel-network

networks:
  admin-panel-network:
    driver: bridge
